CREATE TYPE gender_type AS ENUM (
  'male',
  'female',
  'other'
);

CREATE TYPE login_strategy AS ENUM (
  'local',
  'facebook',
  'twitter',
  'google'
);

CREATE TYPE post_type AS ENUM (
  'text',
  'video',
  'image',
  'audio',
  'link',
  'poll'
);

CREATE TYPE goal_type AS ENUM (
  'subscription_count',
  'money',
  'donation_count'
);

CREATE TYPE benefit_period AS ENUM (
  'one_time',
  'monthly'
);

CREATE TYPE card_brand_type AS ENUM (
  'jcb',
  'visa',
  'mastercard',
  'american_express',
  'diners_club'
);

CREATE TABLE users (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar UNIQUE,
  email varchar,
  password varchar,
  verified bool,
  social_id varchar,
  strategy login_strategy,
  avatar varchar,
  gender gender_type,
  refresh_token varchar,
  created_at timestamptz,
  updated_at timestamptz
);


CREATE TABLE files (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location varchar UNIQUE,
  size int8,
  file_name varchar,
  mime_type varchar,
  created_at timestamptz,
  updated_at timestamptz,
  user_id int8,
  meta jsonb
);






CREATE TABLE user_profiles (
  first_name varchar,
  last_name varchar,
  phone_number varchar,
  bio text,
  updated_at timestamptz,
  user_id int8 PRIMARY KEY 
);

CREATE TABLE user_infos (
  user_id int8 PRIMARY KEY,
  last_logged_in_date timestamptz,
  last_logged_in_ip varchar,
  created_ip varchar
);

--TODO commissions,aka shop;
CREATE TABLE categories (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  banner varchar,
  name varchar,
  description varchar,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE creator_ranks (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fee float8,
  name varchar,
  importance int4
);

CREATE TABLE creators (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  avatar varchar REFERENCES files(location),
  user_id int8 REFERENCES users,
  creator_rank_id int4,
  is_company bool,
  is_nsfw bool,
  stripe_account_id varchar,
  updated_at timestamptz,
  created_at timestamptz
);

CREATE TABLE creator_profiles (
  legal_first_name varchar,
  legal_last_name varchar,
  legal_company_name varchar,
  bio text,
  -- earning_visibility          bool,
  -- subscriber_count_visibility bool,
  creator_id int8 PRIMARY KEY REFERENCES creators ON DELETE CASCADE
);

CREATE TABLE projects (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  page_url varchar,
  description text,
  creating text,
  banner varchar REFERENCES files(location),
  avatar varchar REFERENCES files(location),
  creator_id int8 REFERENCES creators,
  category_id int4 REFERENCES categories,
  setting jsonb,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE project_infos (
  project_id int8 PRIMARY KEY REFERENCES projects
);


CREATE TABLE accesses (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  setting jsonb
);

-- CREATE TABLE project_access (
--   project_id int8 REFERENCES project ON DELETE CASCADE,
--   user_id int8 REFERENCES users ON DELETE CASCADE,
--   access_id int8 REFERENCES access,
--   PRIMARY KEY (project_id, user_id, access_id)
-- );
-- CREATE TABLE site_access (
--   user_id int8 REFERENCES users ON DELETE CASCADE,
--   access_id int8 REFERENCES access,
--   PRIMARY KEY (project_id, user_id, access_id)
-- );
CREATE TABLE creator_accesses (
  creator_id int8 REFERENCES creators ON DELETE CASCADE,
  user_id int8 REFERENCES users ON DELETE CASCADE,
  access_id int8 REFERENCES accesses,
  PRIMARY KEY (creator_id, user_id, access_id)
);

CREATE TABLE tiers (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar,
  description text,
  cover varchar REFERENCES files(location),
  price float8,
  project_id int8 REFERENCES projects ON DELETE CASCADE,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE subscriptions (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int8,
  expiry_date timestamptz,
  tier_id int8,
  created_at timestamptz,
  will_renew bool,
  meta jsonb,
  UNIQUE (user_id, tier_id)
);

CREATE TABLE posts (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar,
  content text,
  mature bool,
  project_id int8,
  submit_user_id int8,
  created_at timestamptz,
  updated_at timestamptz,
  min_price float8
);

CREATE TABLE post_votes (
  user_id int8,
  vote int4,
  post_id int8,
  created_at timestamptz,
  PRIMARY KEY (user_id, post_id)
);

CREATE TABLE comments (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int8 ,
  content text,
  parent_id int8,
  post_id int8,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE comment_votes (
  user_id int8,
  vote int4,
  comment_id int8 ,
  created_at timestamptz,
  PRIMARY KEY (user_id, comment_id)
);



CREATE TABLE tags (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  created_at timestamptz
);

CREATE TABLE post_tags (
  post_id int8 ,
  tag_id int8 ,
  PRIMARY KEY (tag_id, post_id)
);

-- TODO BELOW
CREATE TABLE post_poll_options (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  post_id int8
);
-- CREATE TABLE post_tier (
--   post_id int8 ,
--   tier_id int8,
--   PRIMARY KEY (post_id, tier_id)
-- );

CREATE TABLE post_texts (
  post_id int8 PRIMARY KEY,
  word_count int8,
  char_count int8
);
CREATE TABLE post_poll_answers (
  user_id int8,
  post_poll_option_id int8 ,
  PRIMARY KEY (user_id, post_poll_option_id)
);

CREATE TABLE post_files (
  post_id int8,
  file_id int8 ,
  attachment bool,
  PRIMARY KEY (post_id, file_id)
);

CREATE TABLE post_links (
  post_id int8 primary key,
  link varchar
);

CREATE TABLE goals (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  goal float8,
  TYPE goal_type,
  project_id int8,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE benefits (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text,
  type benefit_period,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE tier_benefits (
  tier_id int8 ,
  benefit_id int8,
  PRIMARY KEY (tier_id, benefit_id)
);

CREATE TABLE payment_methods (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar,
  created_at timestamptz,
  updated_at timestamptz,
  user_id int8,
  default_method bool
);

CREATE TABLE stripe_card_payment_methods (
  payment_method_id int8 PRIMARY KEY,
  last_four int4,
  brand card_brand_type,
  expire_date timestamptz,
  stripe_payment_method_id varchar
);

-- CREATE TABLE stripe_bank_payment_method (
--   payment_method_id int8 PRIMARY KEY REFERENCES payment_method ON DELETE CASCADE,
--   last_four int4,
--   stripe_payment_method_id varchar
-- );

CREATE TABLE payout_methods (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar,
  created_at timestamptz,
  updated_at timestamptz,
  creator_id int8,
  default_method bool
);

CREATE TABLE paypal_payout_methods (
    payout_method_id int8 PRIMARY KEY,
    paypal_email varchar
);

-- CREATE TABLE stripe_card_payout_method (
--   payout_method_id int8 PRIMARY KEY REFERENCES payout_method ON DELETE CASCADE,
--   last_four int4,
--   brand card_brand_type,
--   expire_date timestamptz,
--   stripe_payout_method_id varchar
-- );
-- CREATE TABLE stripe_bank_payout_method (
--   payout_method_id int8 PRIMARY KEY REFERENCES payout_method ON DELETE CASCADE,
--   last_four int4,
--   stripe_payout_method_id varchar
-- );
CREATE TABLE transactions (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount float8,
  sender_id int8,
  receiver_project_id int8,
  created_at timestamptz
);

CREATE TABLE payout_transactions (
  payout_method_id int8,
  transaction_id int8,
  PRIMARY KEY (payout_method_id, transaction_id)
);

CREATE TABLE subscription_transactions (
  subscription_id int8,
  transaction_id int8,
  PRIMARY KEY (subscription_id, transaction_id)
);

CREATE TABLE donation_transactions (
  transaction_id int8 PRIMARY KEY,
  message text,
  name varchar,
  private bool
);

CREATE TABLE messages (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id int8,
  receiver_id int8,
  subject varchar,
  body text,
  created_at timestamptz
);

CREATE TABLE project_page_views (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id int8,
  ip varchar,
  created_at timestamptz
);

CREATE TABLE total_project_views (
  day varchar,
  views int8,
  project_id int8
);

Alter table posts add constraint post_user_fk foreign key (submit_user_id) references users (id) on delete set null;
Alter table posts add constraint post_project_fk foreign key (project_id) references projects (id) on delete cascade;

Alter table comments add constraint comment_user_fk foreign key (user_id) references users (id) on delete cascade;
Alter table comments add constraint comment_parent_fk foreign key (parent_id) references comments (id) on delete cascade;
Alter table comments add constraint comment_post_fk foreign key (post_id) references posts (id) on delete cascade;

Alter table comment_votes add constraint comment_vote_comment_fk foreign key (comment_id) references comments (id) on delete cascade;
Alter table comment_votes add constraint comment_vote_user_fk foreign key (user_id) references users (id) on delete cascade;

Alter table post_links add constraint post_link_post_fk foreign key (post_id) references posts (id) on delete cascade;

Alter table post_texts add constraint post_text_post_fk foreign key (post_id) references posts (id) on delete cascade;

-- Alter table post_tier add constraint post_tier_tier_fk foreign key (tier_id) references tier (id) on delete set null;
-- Alter table post_tier add constraint post_tier_post_fk foreign key (post_id) references posts (id) on delete cascade;

Alter table post_votes add constraint post_vote_post_fk foreign key (post_id) references posts (id) on delete cascade;
Alter table post_votes add constraint post_vote_user_fk foreign key (user_id) references users (id) on delete set null;

Alter table subscriptions add constraint subscription_tier_fk foreign key (tier_id) references tiers (id) on delete set null;
ALTER TABLE subscriptions ADD CONSTRAINT subscription_user_fk foreign key (user_id) references users (id) on delete set null;
ALTER TABLE post_tags ADD CONSTRAINT post_tag_post_fk FOREIGN KEY (post_id) REFERENCES posts (id) on delete cascade;
ALTER TABLE post_tags ADD CONSTRAINT post_tag_tag_fk FOREIGN KEY (tag_id) REFERENCES tags (id) on delete cascade;

ALTER TABLE post_files ADD CONSTRAINT post_file_post_fk FOREIGN KEY (post_id) REFERENCES posts (id) on delete cascade;
ALTER TABLE post_files ADD CONSTRAINT post_file_file_fk FOREIGN KEY (file_id) REFERENCES files (id) on delete cascade;

ALTER TABLE post_poll_options ADD CONSTRAINT post_poll_option_post_fk FOREIGN KEY (post_id) REFERENCES posts (id) on delete cascade;

ALTER TABLE post_poll_answers ADD CONSTRAINT post_poll_answer_user_fk FOREIGN KEY (user_id) REFERENCES users (id) on delete cascade;
ALTER TABLE post_poll_answers ADD CONSTRAINT post_poll_answer_option_fk FOREIGN KEY (post_poll_option_id) REFERENCES post_poll_options (id) on delete cascade;

ALTER TABLE tier_benefits ADD CONSTRAINT tier_benefit_benefit_fk FOREIGN KEY (benefit_id) REFERENCES benefits (id) on delete cascade;
ALTER TABLE tier_benefits ADD CONSTRAINT tier_benefit_tier_fk FOREIGN KEY (tier_id) REFERENCES tiers (id) on delete cascade;

ALTER TABLE users ADD CONSTRAINT user_avatar_fk FOREIGN KEY (avatar) REFERENCES files (location);
ALTER TABLE user_profiles ADD CONSTRAINT user_profile_fk FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE user_infos ADD CONSTRAINT user_info_fk FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE transactions ADD CONSTRAINT transaction_sender_fk FOREIGN KEY (sender_id) REFERENCES users (id) on delete set  NULL;
ALTER TABLE transactions ADD CONSTRAINT transaction_receiver_fk FOREIGN KEY (receiver_project_id) REFERENCES projects (id) on delete set  NULL;

ALTER TABLE payout_transactions ADD CONSTRAINT payout_transaction_fk FOREIGN KEY (transaction_id) REFERENCES transactions (id) on delete cascade;
ALTER TABLE payout_transactions ADD CONSTRAINT payout_transaction_method_fk FOREIGN KEY (payout_method_id) REFERENCES payout_methods (id) on delete set  NULL;

ALTER TABLE subscription_transactions ADD CONSTRAINT subscription_transaction_subscription_fk FOREIGN KEY (subscription_id) REFERENCES subscriptions (id) on delete set  NULL;
ALTER TABLE subscription_transactions ADD CONSTRAINT subscription_transaction_fk FOREIGN KEY (transaction_id) REFERENCES transactions (id) on delete cascade;
ALTER TABLE donation_transactions ADD CONSTRAINT donation_transaction_fk FOREIGN KEY (transaction_id) REFERENCES transactions(id) on delete cascade;

ALTER TABLE payout_methods ADD CONSTRAINT payout_creator_fk FOREIGN KEY (creator_id) REFERENCES creators (id) on delete cascade;

ALTER TABLE files ADD CONSTRAINT file_user_fk FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE messages ADD CONSTRAINT message_sender_fk FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT message_receiver_fk FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE payment_methods ADD CONSTRAINT payment_method_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE stripe_card_payment_methods ADD CONSTRAINT stripe_card_payment_method_fk FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id) ON DELETE CASCADE;

ALTER TABLE paypal_payout_methods ADD CONSTRAINT paypal_payout_method_fk FOREIGN KEY (payout_method_id) REFERENCES payout_methods (id) ON DELETE CASCADE;


ALTER TABLE goals ADD CONSTRAINT goal_project_fk FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;

ALTER TABLE creators ADD CONSTRAINT creator_creator_rank_fk FOREIGN KEY (creator_rank_id) REFERENCES creator_ranks (id) ON DELETE set NULL;

ALTER TABLE total_project_views ADD CONSTRAINT total_project_view_project_fk FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE set NULL;

CREATE UNIQUE INDEX email_unique_idx ON users (LOWER(email));

CREATE UNIQUE INDEX username_unique_idx ON users (LOWER(username));
